### ISSUE TITLE
about SFDA-FSM

### ISSUE THREAD

**Issue by yanjiawei666** [henryccl/FPNet#1]
about ‘Source free domain adaptation for medical image segmentation with fourier style mining’
Hello, I'm sorry to bother you. I noticed that you have reproduced this paper, and I'm wondering if I can ask you a few questions.

Firstly, I would like to ask if you trained the source model by writing your own code or using DeepLabv2?

The second question is what you used for the pre training model in deeplabv2. Is it resnet101? I don't know why I reported an error when using it to train my source model. There was a loading problem
您好打扰您一下，我看到您复现了这篇论文，有几个问题不知道能否请教下您。
首先，我想问一下源模型您是自己写代码训练的吗，是用deeplabv2训练的吗？
第二个问题是您在deeplabv2中的预训练模型用的什么。是resnet101的吗，不知道为什么我在使用他去训练我的源模型时会报错加载有问题

**Comment by henryccl** [comment]
你好，我并未完全复现该论文的结果，我只是简单跑通了整个baseline。文章中很多细节没有提到，包括部分超参数，数据集的具体划分方式等等，因此复现论文中的结果是有难度的。
在我的实现中，源模型是使用的deeplabv3+，backbone是res101。我记得整个baseline好像是有点小问题，但是不难解决，稍微调整就好了。
